# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        # Fix 2: Tells the setup action where to find the lock file for cache key generation.
        # Assuming you are using package-lock.json (for npm ci). Change this path if using yarn.lock.
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies (npm ci)
      run: npm ci
      # Fix 3: Executes the command inside the 'frontend' directory.
      working-directory: frontend
    
    - name: Build
      run: npm run build --if-present
      # Fix 4: Executes the command inside the 'frontend' directory.
      working-directory: frontend
    
    - name: Run tests
      run: npm test
      # Fix 5: Executes the command inside the 'frontend' directory.
      working-directory: frontend

